# Generated by Django 6.0.7 on 2026-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='des',
            field=models.TextField(default='fasdfasdfas'),
            preserve_default=False,
        ),
    ]
